/* 由后台自动生成，请勿手改 */
window.MOTION_PROJECTS = [
  {
    "id": "01",
    "name": "DSC_2324",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/DSC_2324.JPG.webp",
    "thumb": "images/motion/DSC_2324.JPG-thumb.webp"
  },
  {
    "id": "02",
    "name": "DSC_2342",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/DSC_2342.JPG.webp",
    "thumb": "images/motion/DSC_2342.JPG-thumb.webp"
  },
  {
    "id": "03",
    "name": "DSC_2351",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/DSC_2351.webp",
    "thumb": "images/motion/DSC_2351-thumb.webp"
  },
  {
    "id": "04",
    "name": "DSC_2361",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/DSC_2361.webp",
    "thumb": "images/motion/DSC_2361-thumb.webp"
  },
  {
    "id": "05",
    "name": "DSC_2365",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/DSC_2365.JPG.webp",
    "thumb": "images/motion/DSC_2365.JPG-thumb.webp"
  },
  {
    "id": "06",
    "name": "DSC_2386",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/DSC_2386.webp",
    "thumb": "images/motion/DSC_2386-thumb.webp"
  },
  {
    "id": "07",
    "name": "DSC_2455",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/DSC_2455.webp",
    "thumb": "images/motion/DSC_2455-thumb.webp"
  },
  {
    "id": "08",
    "name": "DSC_2482",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/DSC_2482.NEF.webp",
    "thumb": "images/motion/DSC_2482.NEF-thumb.webp"
  },
  {
    "id": "09",
    "name": "DSCF4777",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/DSCF4777.JPG.webp",
    "thumb": "images/motion/DSCF4777.JPG-thumb.webp"
  },
  {
    "id": "10",
    "name": "IMG_0116",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/IMG_0116.webp",
    "thumb": "images/motion/IMG_0116-thumb.webp"
  },
  {
    "id": "11",
    "name": "IMG_0122",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/IMG_0122.webp",
    "thumb": "images/motion/IMG_0122-thumb.webp"
  },
  {
    "id": "12",
    "name": "IMG_0194",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_0194.webp",
    "thumb": "images/motion/IMG_0194-thumb.webp"
  },
  {
    "id": "13",
    "name": "IMG_0236",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/IMG_0236.webp",
    "thumb": "images/motion/IMG_0236-thumb.webp"
  },
  {
    "id": "14",
    "name": "IMG_0276",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/IMG_0276.webp",
    "thumb": "images/motion/IMG_0276-thumb.webp"
  },
  {
    "id": "15",
    "name": "IMG_0349",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_0349.webp",
    "thumb": "images/motion/IMG_0349-thumb.webp"
  },
  {
    "id": "16",
    "name": "IMG_0370",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_0370.webp",
    "thumb": "images/motion/IMG_0370-thumb.webp"
  },
  {
    "id": "17",
    "name": "IMG_0462",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_0462.webp",
    "thumb": "images/motion/IMG_0462-thumb.webp"
  },
  {
    "id": "18",
    "name": "IMG_0473",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_0473.webp",
    "thumb": "images/motion/IMG_0473-thumb.webp"
  },
  {
    "id": "19",
    "name": "IMG_0716",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/IMG_0716.CR3.webp",
    "thumb": "images/motion/IMG_0716.CR3-thumb.webp"
  },
  {
    "id": "20",
    "name": "IMG_0822",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_0822.webp",
    "thumb": "images/motion/IMG_0822-thumb.webp"
  },
  {
    "id": "21",
    "name": "IMG_0844",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_0844.webp",
    "thumb": "images/motion/IMG_0844-thumb.webp"
  },
  {
    "id": "22",
    "name": "IMG_0948",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_0948.webp",
    "thumb": "images/motion/IMG_0948-thumb.webp"
  },
  {
    "id": "23",
    "name": "IMG_1030",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/IMG_1030.webp",
    "thumb": "images/motion/IMG_1030-thumb.webp"
  },
  {
    "id": "24",
    "name": "IMG_1114",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/IMG_1114.webp",
    "thumb": "images/motion/IMG_1114-thumb.webp"
  },
  {
    "id": "25",
    "name": "IMG_1165",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_1165.JPG.webp",
    "thumb": "images/motion/IMG_1165.JPG-thumb.webp"
  },
  {
    "id": "26",
    "name": "IMG_1258",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/IMG_1258.webp",
    "thumb": "images/motion/IMG_1258-thumb.webp"
  },
  {
    "id": "27",
    "name": "IMG_1268",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/IMG_1268.JPG.webp",
    "thumb": "images/motion/IMG_1268.JPG-thumb.webp"
  },
  {
    "id": "28",
    "name": "IMG_2890",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_2890.JPG.webp",
    "thumb": "images/motion/IMG_2890.JPG-thumb.webp"
  },
  {
    "id": "29",
    "name": "IMG_2922",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_2922.JPG.webp",
    "thumb": "images/motion/IMG_2922.JPG-thumb.webp"
  },
  {
    "id": "30",
    "name": "IMG_3070",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_3070.JPG.webp",
    "thumb": "images/motion/IMG_3070.JPG-thumb.webp"
  },
  {
    "id": "31",
    "name": "IMG_4838",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "landscape",
    "img": "images/motion/IMG_4838.webp",
    "thumb": "images/motion/IMG_4838-thumb.webp"
  },
  {
    "id": "32",
    "name": "IMG_4859",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_4859.JPG.webp",
    "thumb": "images/motion/IMG_4859.JPG-thumb.webp"
  },
  {
    "id": "33",
    "name": "IMG_4861",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_4861.JPG.webp",
    "thumb": "images/motion/IMG_4861.JPG-thumb.webp"
  },
  {
    "id": "34",
    "name": "IMG_4884",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_4884.JPG.webp",
    "thumb": "images/motion/IMG_4884.JPG-thumb.webp"
  },
  {
    "id": "35",
    "name": "IMG_4911",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_4911.JPG.webp",
    "thumb": "images/motion/IMG_4911.JPG-thumb.webp"
  },
  {
    "id": "36",
    "name": "IMG_4960",
    "kind": "PHOTO",
    "year": "—",
    "shot": "—",
    "location": "待补充",
    "camera": "待补充",
    "desc": "",
    "story": "在这里写下这张照片的故事……",
    "orientation": "portrait",
    "img": "images/motion/IMG_4960.JPG.webp",
    "thumb": "images/motion/IMG_4960.JPG-thumb.webp"
  }
];
